trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install dependencies'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'

- script: mkdir -p test-results
  displayName: 'Create test-results directory'

- script: npx playwright test --reporter=junit --reporter-options outputFile=test-results/results.xml; exit 0
  displayName: 'Run Playwright tests'
  continueOnError: true
  env:
    CI: 'true'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results/results.xml'
    failTaskOnFailedTests: true 